### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by Unargent** [eukara/FreeCS#11]
- cs_italy

![italychickenmissingtextures](https://user-images.githubusercontent.com/106993968/194596337-6fa34b88-efb8-43d3-851f-28dd4d558126.png)
![italybottlesmissingtextures](https://user-images.githubusercontent.com/106993968/194596363-cb856d58-3ae7-4995-addd-7d3495c0aa19.png)

- de_survivor

![survivormissingtexture2](https://user-images.githubusercontent.com/106993968/194596579-19498225-20a9-4309-8e37-1cc229e10222.png)
![survivormissingtexture](https://user-images.githubusercontent.com/106993968/194596586-31da2788-e03b-42c1-956c-6224e93200b5.png)

- de_vegas

![vegasmissingtexture4](https://user-images.githubusercontent.com/106993968/194596698-c0ce053d-6c26-4fa0-9d4d-c842e75e9f34.png)
![vegasmissingtexture3](https://user-images.githubusercontent.com/106993968/194596707-b76e152d-8b6d-4ed7-935b-43f62fa44257.png)
![vegasmissingtexture2](https://user-images.githubusercontent.com/106993968/194596710-10f32337-b8b9-41aa-ad2a-564bdae46378.png)
![vegasmissingtexture](https://user-images.githubusercontent.com/106993968/194596713-e8a24a44-3535-41c2-9d38-f4331b66e89f.png)

**Comment by atomGit** [comment]
deleted

never mind - i've been possessed by stupidity (again)

**Comment by eXPc023** [comment]
These aren't missing textures but entities which weren't meant to be seen. Entities use aaatrigger (what you see on the boxes) texture.

**Comment by eukara** [comment]
This issue was fixed but I forgot to close it. Sorry!
