### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by kwadroke** [eukara/FreeCS#15]
What commands are used to build from source? So far I haven't found any instructions on how to do this.

**Comment by st1x51** [comment]
Use fteqcc or fteqccgui for compiling QC src.
Its can be found here http://triptohell.info/moodles/win32/
put compiler near progs.src file(Client,Server or Menu folder)

**Comment by kwadroke** [comment]
Thanks.
Perhaps this should be in a compiling doc somewhere for future reference?
