### ISSUE TITLE
Weapon missing when looking at other players 

### ISSUE THREAD

**Issue by kwadroke** [eukara/FreeCS#16]
When looking at another player, their weapon models are not shown.

I'm sure this is a known issue, but, I wanted to make sure this gets fixed. :)

**Comment by eukara** [comment]
This requires skeletalobjects to work on HL MDL models. This will be enabled as soon as that happens.

**Comment by eukara** [comment]
Developed a system using gettaginfo that will bring them in the game. Sort of. It works decent enough.
