### ISSUE TITLE
Music continues to play after a broken player (cs_italy)

### ISSUE THREAD

**Issue by Unargent** [eukara/FreeCS#16]
https://user-images.githubusercontent.com/106993968/194599439-7bf5f1ff-a06a-4d01-854a-fc35c7eb6c7c.mp4

**Comment by atomGit** [comment]
unable to reproduce

**Comment by eukara** [comment]
Yeah I've done a lot of work on ambient_generic in Nuclide since then. Thanks for letting me know!
