### ISSUE TITLE
Game crashes into console after successfull bomb detonation

### ISSUE THREAD

**Issue by poVoq** [eukara/FreeCS#17]
Under Linux running the 5th of June FTEQW binaries, the game crashes into the console when when the bomb detonates successfully. As the console is getting spammed even before that with "console eInput read -1" no specific error message can be seen.

**Comment by eukara** [comment]
Will look into this as soon as I have a Linux machine running again.

**Comment by poVoq** [comment]
fixed with new FTEQW binaries from the 23 of June 2017.
