### ISSUE TITLE
Menu input only works in windowed mode under Linux

### ISSUE THREAD

**Issue by poVoq** [eukara/FreeCS#18]
Using the latest FTEQW binaries from the 5th of June, the menu can not be used as no keyboard or mouse input is recognized unless I edit the default.cfg to start the game in windowed mode.

**Comment by poVoq** [comment]
In general: any reason you are not using the menusys framework that comes with FTEQW? It seems to work well on my project and comes with all the nice additional things like irc and xmpp integration via the plugins.

**Comment by kwadroke** [comment]
I think I was having the same issue on older releases of FTEQW - The mouse pointer was too small. I too worked around the issue by using Windowed mode on Linux.

**Comment by eukara** [comment]
That's some Linux issue on FTEQWs part. I will have to see what I can do to work around it until Spike fixes it.

**Comment by poVoq** [comment]
with the latest updates it works until the fist click or alternatively something like 5 seconds. Mousewheel seems to continue working.

The strange thing is that with my non-related FTEQW menusys game it works fine, but initially I had the same issue which somehow disappeared after adding the FTE target in the menu.scr.

**Comment by poVoq** [comment]
Still the same with the 2017-08-10 FTEQW binaries :(
Any idea if this will ever get fixed?

**Comment by APGSans** [comment]
same issue. any workarounds?

**Comment by eukara** [comment]
Added a workaround. Works on KDE5 for me now. Will test if it affects any Windows builds. It's kind of dirty but it will have to do.

I am updating mouse deltas while offering absolute positions too whenever the engine sends them. I am doing my part as far as QuakeC is concerned so the problem lies in the engine supporting Linux not well

**Comment by poVoq** [comment]
thanks that fixed it!!!
