### ISSUE TITLE
csbeta_6.0_to_6.1.zip is missing from archive.org

### ISSUE THREAD

**Issue by Danfun64** [eukara/FreeCS#2]
I'm not sure if it was deleted or simply hasn't been uploaded, but this patch is missing from your archive.org uploads.

**Comment by eukara** [comment]
Thanks for noticing! Sometimes the archive.org uploader just doesn't grab everything - I'm not sure what that's about. It happened on Frag-Net's Action Quake 2 page as well. _It should be fixed now!_
