### ISSUE TITLE
Fix the hostage pathfinding

### ISSUE THREAD

**Issue by eukara** [eukara/FreeCS#22]
That stuff keeps regressing and getting worse and worse.
I don't want to do anything expensive right now, just something that makes them playable and not get stuck everywhere.

**Comment by poVoq** [comment]
Maybe worth looking into bots in general? One could create waypoint files for the maps that would also benefit a frikbot implementation.

**Comment by eukara** [comment]
Once the code-base is feature-complete I will totally look into bots. It will probably be an external progs.

**Comment by eukara** [comment]
I will probably port PODBot. Frikbot is not suited for this type of game.
