### ISSUE TITLE
Switching to same slot replays last animation

### ISSUE THREAD

**Issue by 9cg** [eukara/FreeCS#3]
![unknown](https://user-images.githubusercontent.com/52229396/152272527-ae823733-925d-4978-a7b7-b9cc419644cf.gif)

**Comment by atomGit** [comment]
wasn't this a "bug" in older official versions of CS? if so, i would vote for keeping this particular "bug" for nostalgic reasons

**Comment by eukara** [comment]
It's been fixed. Sorry it took so long, I was hoping to simplify some of the HUD/Weapon code that's intertwined but I just never got around to it. It's a 1 line diff anyway.
