### ISSUE TITLE
Can't buy secondary ammunition for machine guns

### ISSUE THREAD

**Issue by poVoq** [eukara/FreeCS#38]
Somehow I thought this was working, but in my test 5 minutes ago it was not possible to buy secondary ammunition... at least not for machine-pistols.

Edit: ok this is a bit odd. It works in some constellations but in others not. If the first thing you buy is a HK and then try to buy secondary it does not, but when buying other things first, or a MP5 or so, it seems to work.

Edit2: Consistently replicatable under Linux GL:
Start de_dust, join terrorists. go plant bomb. wait for round to end.
New round, press buy menu, buy HK UMP45.
press buy menu again, buy secondary ammunition.
First time you try $100 as subtraction pops up, but you don't get extra ammo. Any further try just does nothing.

**Comment by eukara** [comment]
Pistols use secondary ammo, none of the other weapons do. So when you get the $100 notification you have filled up your pistol ammo to the max, hence why you cannot buy more the second time.

**Comment by poVoq** [comment]
Arg, right. That was stupid :( Long time since I last played CS.
