### ISSUE TITLE
Picking up weapons?

### ISSUE THREAD

**Issue by poVoq** [eukara/FreeCS#40]
Weapons get dropped fine when buying new ones from the same category, but if I remember correctly it was possible in CS to pick up weapons your team-mates dropped.

**Comment by eukara** [comment]
It's meant to work like this as of now:
If you already got a weapon in that slot, you won't pick a weapon up that's on the floor.
If you want to switch your e.g. pistol with someones Deagle, press G (default) while having the pistol equipped and run over it

**Comment by poVoq** [comment]
Somehow I remember there was a prompt for picking up weapons, but maybe that was added after 1.5?
