### ISSUE TITLE
Level loading takes really long with 1/11/2017 FTE release

### ISSUE THREAD

**Issue by poVoq** [eukara/FreeCS#42]
Something got broken with the latest FTE release from the 1st of November. When I create a server the loading bar stays at 0% for a long time, then disappears completely, and after a really long time (I thought it would not load at all) the level starts.

**Comment by eukara** [comment]
I have not experienced these hiccups. Either way, this page is not meant for FTE QuakeWorld specific bug reports. I have informed Spike though.

**Comment by poVoq** [comment]
@Shpoike
Still not fixed with the 05/11/2017 binaries. It seems rather odd, but if I press ESC a few times (mouse pointer appears then) it seems to speed up.

I also tried with the windows release using WINE and there this error does not appear.

According to the console the waiting happens between the "Server spawned" and the client connected message.

Before that I get these errors:

> NET_SendPollPacket ERROR: 101
> NET_SendPollPacket ERROR: 101
> NET_SendPollPacket ERROR: 101
> NET_SendPollPacket ERROR: 101
> Couldn't find spawn function for infodecal
> Couldn't find spawn function for env_sound

Other than that it just complains about "Unable to load libSDL2 library" on my Kubuntu 16.04 system.

Any idea?
