### ISSUE TITLE
Enable XMPP plugin for voicechat?

### ISSUE THREAD

**Issue by poVoq** [eukara/FreeCS#43]
Is it possible to enable the FTEQW XMPP plugin somehow?

IRC would be nice as well.

**Comment by poVoq** [comment]
Ok manually you can do:
 /menu_download

Then download & enable the XMPP plugin

Then type /xmpp in the console.

Would be cool it it was included by default and accessible through the menu.

**Comment by eukara** [comment]
You can also use Opus and Speex for voice chat.

**Comment by poVoq** [comment]
Aren't those just the codex used for compressing the voice chat established through XMPP?

**Comment by Shpoike** [comment]
I think what he's saying is that you can use voip via the game server instead of needing to set up xmpp accounts etc, and that way other players can hear too (just bind something to +voip and you're done).
obviously that's no substitute for setting up game connections, but hey.

**Comment by poVoq** [comment]
Ah, I wasn't aware that this option also exists. Is it documented somewhere in more detail?

**Comment by eukara** [comment]
bind v +voip
And it'll automatically detect the codec you have compiled into FTE. It will use Opus by default.

Some cvars!
Choose the codec:
snd_voip_codec 0/1/2/3
0 = Auto
1 = Opus
2 = Speex (Narrow)
3 = Speex (Wide)

Voice playback volume:
snd_voip_play 0.0-1.0

Test Microphone (hear yourself):
snd_voip_test 0/1

Noise cancellation:
snd_voip_noisefilter 0/1
