### ISSUE TITLE
Tiny menu/fonts on FullHD screen

### ISSUE THREAD

**Issue by poVoq** [eukara/FreeCS#44]
As FULL HD screen are more or less the default these days, it would be nice if a higher value of /vid_conautoscale was made default.

/vid_conautoscale 2 is maybe slightly big, but seems to work well.

**Comment by poVoq** [comment]
https://github.com/eukara/FreeCS/pull/45

**Comment by eukara** [comment]
I myself sadly have to work with a tiny screen. So that pull request is counter-intuitive for me and also anyone using Portable devices trying it out. You'd be better off setting vid_conwidth to 640 and vid_conheight to 0 if you want it to auto-scale everything

**Comment by poVoq** [comment]
Not sure I follow. This is for small screens with high resolution like the majority of devices today.

But I guess it it better turned into a config setting with values of 1, 1.5, and 2.

**Comment by Shpoike** [comment]
640*auto scales to 4k resolutions better than width/2*height/2. the former shows the menu over the entire screen (ish, to maintain aspect), the latter uses about 1/16th of the screen (assuming menus made for 640*480 res).

regarding the console font, I'm a fan of con_textsize -12, which gives size in pixels and ignores random rescaling. most ttf fonts require 12 pixels. this gives the best control over it.

**Comment by eukara** [comment]
Uhm. Uhh. Added an option. I just call it the HDPI mode. Should have called it Retina mode, that'll show 'em
