### ISSUE TITLE
CS 1.5 servers

### ISSUE THREAD

**Issue by schvabodka-man** [eukara/FreeCS#57]
Hello there! Just simple questions(can't find answers in readme/faq). Is it possible to play it on "regular" CS 1.5 servers or there must be some specific server supporting FreeCS(i was hearing that freecs has physics that somehow different from vanilla 1.5)? Is there only client or there is a open source CS 1.5 server implementation(or planned)? Are there bots(or any bots implementation planned)?

**Comment by Calinou** [comment]
FreeCS, as it is based on [FTEQW](http://fte.triptohell.info/), uses the QuakeWorld protocol, and is not compatible with CS 1.5 servers.

You can host a dedicated server by getting the data files (it's best to place your FreeCS installation into a `.zip` archive, send it to the server using something like `scp`, download a server binary from [the FTEQW downloads page](http://fte.triptohell.info/index.php?p=downloads) then start up the server). To make it appear on the server list, add the line `seta sv_public 1` to `freecs/ftesrv.cfg`.

Bots are planned, see [this issue](https://github.com/eukara/FreeCS/issues/37) for details.

**Comment by schvabodka-man** [comment]
Are there any plans to implement abstraction for vanilla CS protocol to add possibility to connect to 1.5 servers?

**Comment by Shpoike** [comment]
No. That'd pretty much require gamecode compat too, which is a much greater undertaking.
Besides, it'd probably just result in flaming about making cheats freely available or something.
