### ISSUE TITLE
Unable to burst shoot glock with less than 3 rounds in magazine

### ISSUE THREAD

**Issue by ObscureScience** [eukara/FreeCS#77]
As of commit  56abd06 ( and since I first tried FreeCS a couple of days ago) you cannot fire the glock when in burst mode with less than 3 rounds in the magazine. I cannot recall if this was the case in any previous version of the original but I assume not.

**Comment by eukara** [comment]
CS 1.5 Behaviour:
Burst shoot whatever is left in the magazine.

**Comment by ObscureScience** [comment]
So the incorrect behavior starts [here](https://github.com/eukara/FreeCS/blob/56abd0648150caadba264c35507f90ba99b69089/Source/Shared/WeaponGlock18.c#L92) i presume?

**Comment by eukara** [comment]
Fixed in 
https://github.com/eukara/FreeCS/commit/ee80ee94396d93dd573293164d206ea577c9f73e

**Comment by ObscureScience** [comment]
Just to clarify, as I have not read through the code other than to find this specific piece, is it correct to call `BaseGun_ShotMultiplierHandle( 3 );` rather than `BaseGun_ShotMultiplierHandle( self.iMag_GLOCK18 );` ?

**Comment by eukara** [comment]
Only if iMag_GLOCK18 truly was below 3... which most of the time it isn't
I forgot to adapt the values though. Will be fixed in the next commit

**Comment by eukara** [comment]
Actually, that line shouldn't be called at all, considering BaseGun_ShotMultiplierHandle( 1 ); is called inside the for loop...

**Comment by eukara** [comment]
As for the clientside logic, it would not exactly know how many bullets were successfully shot once the event call arrives. Possibly something I'd want to look into
