### ISSUE TITLE
Unable to join a specific server game with "Progs boundcheck failed. Value is 19."

### ISSUE THREAD

**Issue by ObscureScience** [eukara/FreeCS#78]
When trying to join a server (Calinou's) that is up as of 2017/11/19  18:51 GMT+1 connection is aborted after entering the game and choosing side with above error.
[qconsole.log](https://github.com/eukara/FreeCS/files/1485802/qconsole.log)

Edit: removed server ip from this description, realized it's probably the hosts private ip. Sorry about that.

**Comment by kwadroke** [comment]
Think this is a version conflict. I got the same thing running the latest commit.

**Comment by Calinou** [comment]
It was probably a problem on my side, I've updated the server and tested with a local client, and it seems to work again.

This issue should be closed, as it is not a problem with FreeCS itself.
