### ISSUE TITLE
Death animations looped

### ISSUE THREAD

**Issue by Unargent** [eukara/FreeCS#8]
After the corpses have disappeared from view, their death animation is replayed if you look at them again.

https://user-images.githubusercontent.com/106993968/188643359-17611d32-85d1-4dc4-a342-b0c517e59b32.mp4

Tested on:
Commits: https://github.com/eukara/freecs/commit/e744c22f40992acdab75b299e7c2140bd4da545468
https://github.com/eukara/freehl/commit/5b9db50f2c40778d36e318ca55a672f6e938b49c
https://github.com/VeraVisions/nuclide/commit/9deb12b68de6485285c81975d20eb93dc9af547b
OS: Debian 11
Backend: SDL2
Render type: OpenGL
Data files: Shareware (from the script)

**Comment by eukara** [comment]
Fixed in Nuclide commit https://github.com/VeraVisions/nuclide/commit/28389846034fd4eda326979d92fb0cbdbd7fd9b1
