### ISSUE TITLE
Configuration not saved after exiting game

### ISSUE THREAD

**Issue by kwadroke** [eukara/FreeCS#81]
After configuring keybinds via the GUI the data isn't saved when the game exited. This requires the user to rebind the keys each time the game is played.

OS: Linux - Debian 8
FTE Version - Latest build as of this posting
FreeCS Version - Latest build as of this posting

**Comment by eukara** [comment]
Delete your current fte.cfg/config.cfg.
Your old config probably conflicts with the default.cfg
https://github.com/eukara/FreeCS/blob/master/freecs/default.cfg#L80
I changed to cfg_save_auto "1"at some point recently. If you had any configs before that change it might revert to 0.

**Comment by kwadroke** [comment]
Thanks. Will do that tonight.

**Comment by kwadroke** [comment]
Ok. Removed fte.cfg and the config saves.
