### ISSUE TITLE
Terrorists can buy defusal kit

### ISSUE THREAD

**Issue by roofstompa** [eukara/FreeCS#82]
Didn't check if it helps them defuse though :)
Edit: It appears that any team can buy any item meant for opposite team.

**Comment by eukara** [comment]
https://github.com/eukara/FreeCS/commit/3333ebc9812d7a0ec87a30ab64d65779083042f7
Fixed with this

**Comment by eukara** [comment]
Not even really a bug, it was an oversight. I wrote a TODO for it inside the sources (can be seen in the commit) but I have always skipped over it it seems.

**Comment by kwadroke** [comment]
Just curious/Devil's Advocate, What if there was a new scenario/map where CT's bomb a T's base?

**Comment by eukara** [comment]
https://github.com/eukara/FreeCS/issues/83

Let's put gamemode ideas into one place :D
