### ISSUE TITLE
Menu not working correctly when in fullscren

### ISSUE THREAD

**Issue by hameliner** [eukara/FreeCS#85]
Hey there!
It's like a dream has come for real! More than ten years ago I needed this ;-)

It's working nicely here - but just in windowed mode. If I enter the main menu right after start in fullscreen, it's rather small and now the bug: I can not select anything. The mouse over hover effect does not work then, too - just the first time when I hover it ... suddenly it stops working. The only thing I can do then is: open console and start a map via "map de_dust" cmd stuff.
Please fix it so the menu system works in fullscreen.

My System:
Manjaro (Arch) Linux with bleeding edge up to date packages.

Linux: 4.9.65-1-MANJARO #1 SMP PREEMPT Fri Nov 24 10:42:19 UTC 2017 x86_64 GNU/Linux
8 GB RAM

FTE SVN 5133
Setting mode 1920*1080*24*0 OpenGL
Using XF86-VidModeExtension Ver. 2.2
Window manager "Xfwm4" supports fullscreen
GL_VENDOR: Intel Open Source Technology Center
GL_RENDERER: Mesa DRI Intel(R) Haswell Mobile 
GL_VERSION: 3.0 Mesa 17.2.5
Video mode 1920x1080 initialized.
Gone fullscreen
W_LoadWadFile: Wad file gfx.wad doesn't have WAD2 id
Initing default SDL audio device.
OpenGL renderer initialized

We would need more servers / players, too ;-)

**Comment by eukara** [comment]
Your build of FTE QuakeWorld is several revisions old. This bug was fixed around the end of October. I added a hack back in https://github.com/eukara/FreeCS/issues/18 but FTE has since resolved the issue internally.

**Comment by hameliner** [comment]
Ok. Problem was the fteqw**-gl**64 binary.
Well then - the newest fteqw64 binary for linux works fantastic.
Remains the problem that there are no servers around. Too sad. We need propaganda ;-)
