### ISSUE TITLE
Texture precaching issues with maps

### ISSUE THREAD

**Issue by appleinsanity** [eukara/FreeCS#95]
Most of the time the textures for maps won't load and it loads the standard grey replacement texture instead. After typing vid_restart it will be fixed.

**Comment by eukara** [comment]
Are all the wad filenames lowercase?

**Comment by appleinsanity** [comment]
Yeah, I didn't notice. That fixed it. Thank you very much.
But is there a way to make the client search for the right extentions?

**Comment by eukara** [comment]
That's something FTEQW has to support.
It's meant to index files that way, but yeah it doesn't seem to work as of yet.
